import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb690",
        "surface-container-high": "#2a2a2a",
        "surface-tint": "#7bd0ff",
        "surface-container-low": "#1b1b1b",
        "primary": "#7bd0ff",
        "on-secondary-fixed-variant": "#783200",
        "on-background": "#e2e2e2",
        "on-surface": "#e2e2e2",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#464747",
        "surface-variant": "#353535",
        "surface-bright": "#393939",
        "on-tertiary": "#2f3131",
        "surface-container-lowest": "#0e0e0e",
        "surface-container": "#1f1f1f",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-fixed-dim": "#7bd0ff",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#303030",
        "surface": "#131313",
        "secondary-container": "#ec6a06",
        "tertiary": "#c7c6c6",
        "error": "#ffb4ab",
        "tertiary-container": "#a0a0a0",
        "surface-dim": "#131313",
        "primary-container": "#29abe2",
        "secondary": "#ffb690",
        "outline-variant": "#3e484f",
        "on-secondary-container": "#4a1c00",
        "on-primary-fixed": "#001e2c",
        "surface-container-highest": "#353535",
        "on-secondary": "#552100",
        "on-primary": "#003549",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-tertiary-container": "#363737",
        "inverse-surface": "#e2e2e2",
        "primary-fixed": "#c4e7ff",
        "inverse-primary": "#00668a",
        "on-primary-container": "#003b53",
        "tertiary-fixed": "#e3e2e2",
        "outline": "#88929a",
        "on-secondary-fixed": "#341100",
        "background": "#131313",
        "on-surface-variant": "#bdc8d0",
        "on-primary-fixed-variant": "#004c69",
        "secondary-fixed": "#ffdbca",
        "on-error": "#690005",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "monospace"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config
